# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1797de398c3b228fef23ca84b22e22ccc2ffafa2ae8ff86994bf3ab734f2ae0b87838e3f39d757478707027e30e54a596462bd07cc2c456f04bad2ad3e2a2e1

test:
  secret_key_base: 61db4accafe984f1710a7c47bd4424f1ed80cfe95068d789008b24b813e5e434cdc1266e2d5df2c3693d7cb6177c04c846244b949d7c997edd21203359ee1138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
